### ISSUE TITLE
Problem via All Import

### ISSUE THREAD

**Issue by DAThosting** [haringsrob/Wordpress-Icecat#7]
Your plugin still works on WP 5.0.3.

I made some changes to get it working better (for my shop).

There is only one problem, if I import my products (each 3 hours) the plugin doesn't change text or sth. like that. I checked the config again and can't find a problem.
If I edit the product and click update, the plugin will fetch all data like a charme.

Regards,
Philipp

**Comment by btech69** [comment]
Hello and thanks for the plugin - I'm just wondering if there's a way to trigger a manual update that will force icecat garbber to get images for all products without images in WooCommerce?

**Comment by Marvin-Galileo-Academy** [comment]
> Hello and thanks for the plugin - I'm just wondering if there's a way to trigger a manual update that will force icecat data grabber to get images for all products without images in WooCommerce?

Im running into the same problem. The import cant handle importing images on scale.
Did anyone find a solution?

**Comment by EasyCompZLD** [comment]
it's discontinued my team and I are looking to reanimate this thing since other companies ask over 10,000 euros for a year. Only to gain content to something that they probably obtained for less dan nothing, and also the plugin is almost 900 KB so not so fancy plugin for that price, stupid Ice shit. any other alternative data sources anyone?

**Comment by haringsrob** [comment]
I think that with wp all import they might have changed something in the implementation. This plugin may indeed be behind for that change.

I am no longer maintaining this project, but feel free to open up pull requests.
